address_descriptors = false
author = "La Place Villecroze, Luc Van De Velde"
copyright = "Copyright © 2022 -2023  laplacevillecroze.fr - La Place"
custom_script = ""
description = "Réservez votre Table et Dégustez de Savoureux Plats à la carte ou en menu sous les platanes de Villecroze. Nous vous proposons deux cartes différentes en fonction de ce que vous voulez manger : Plats cuisinés à la carte ou des Pizzas. Venez découvrir nos deux restaurants installer sur la place de Villecroze."
email = "restaurant@laplacevillecroze.fr"
favicon = "/uploads/Favicon/favicon.ico"
google_tag_manager = "G-16QJRXF1P5"
keywords = "restaurant, terrasse, villecroze, var, viande, vente à emporter, La Place, Restaurant La Place,"
location = "9 Pl. Général de Gaulle, 83690 Villecroze"
navbar_fixed = false
phoneRestaurant = "04 94 70 27 24"

[baidu]
analytics_id = ""
enable = false

[contact.form]
action = "#"
enable = false
success_image = "/uploadsimages/paper-plane.svg"
use_netlify = false

[cookies]
button = "I Accept"
content = "This site uses cookies. By continuing to use this website, you agree to their use."
enable = false
expire_days = 2

[counter]
enable = false
username = ""

[gmap]
enable = false
gmap_api = ""
map_latitude = ""
map_longitude = ""
map_marker = "/uploadsimages/marker.png"

[matomo]
enable = false
id = "1"
url = ""

[navigation_button]
enable = false
label = "get a quote"
link = "contact"

[osm]
enable = false
map = ""

[plausible]
domain = ""
enable = false

[preloader]
enable = true
preloader = ""

[site_verification]
baidu = ""
bing = ""
google = ""

[widgets]
sidebar = [ "recent_posts", "taxonomy_category", "taxonomy_tags" ]
