address_descriptors = false
author = "La Place ...A Cote Villecroze, Luc Van De Velde"
copyright = "Copyright © 2022 laplaceacote.fr - La Place ...A Cote"
custom_script = ""
description = "Un enmplacement deux restaurant"
email = "restaurentlaplace@gmail.com"
favicon = "images/favicon.ico"
google_tag_manager = ""
keywords = "restaurant, pizzeria, terrasse, villecroze, var, viande, vente à emporter, La Place, A Coté , Restaurant La Place, Pizzeria A Coté"
location = "9 Pl. Général de Gaulle, 83690 Villecroze"
navbar_fixed = false
phonePizza = "04 94 70 27 24"
phoneRestaurant = "06 30 21 70 26"
[baidu]
analytics_id = ""
enable = false
[contact.form]
action = "#"
enable = false
success_image = "images/paper-plane.svg"
use_netlify = false
[cookies]
button = "I Accept"
content = "This site uses cookies. By continuing to use this website, you agree to their use."
enable = false
expire_days = 2
[counter]
enable = false
username = ""
[gmap]
enable = false
gmap_api = ""
map_latitude = ""
map_longitude = ""
map_marker = "images/marker.png"
[matomo]
enable = false
id = "1"
url = ""
[navigation_button]
enable = false
label = "get a quote"
link = "contact"
[osm]
enable = false
map = ""
[plausible]
domain = ""
enable = false
[preloader]
enable = true
preloader = ""
[site_verification]
baidu = ""
bing = ""
google = ""
[widgets]
sidebar = ["recent_posts", "taxonomy_category", "taxonomy_tags"]
