address_descriptors = false
author = "La Place ...A Cote Villecroze, Luc Van De Velde"
copyright = "Copyright © 2022 laplaceacote.fr - La Place ...A Cote"
custom_script = ""
favicon = "images/favicon.png"
google_tag_manager = ""
keywords = "courtoise, ressourcerie, reemploi, ecolo, recyclage, sived, insertion, collecte, saint-maximin-la-sainte-baume, brignoles"
location = "90 Chemin de Bonneval - Quartier La Courtoise 83470 Saint-Maximin-la-Sainte-Beaume\n"
email = "secretariat@courtoiseressourcerie.com"
description = "Le réemploi, plus écolo que le recyclage"
navbar_fixed = false
phone = "04 94 72 01 50"

[baidu]
analytics_id = ""
enable = false
[contact.form]
action = "#"
enable = false
success_image = "images/paper-plane.svg"
use_netlify = false
[cookies]
button = "I Accept"
content = "This site uses cookies. By continuing to use this website, you agree to their use."
enable = false
expire_days = 2
[counter]
enable = false
username = ""
[gmap]
enable = false
gmap_api = ""
map_latitude = ""
map_longitude = ""
map_marker = "images/marker.png"
[matomo]
enable = false
id = "1"
url = "https://yunohost.courtoiseressourcerie.com/matomo/"
[navigation_button]
enable = false
label = "get a quote"
link = "contact"
[osm]
enable = false
map = ""
[plausible]
domain = ""
enable = false
[preloader]
enable = true
preloader = ""
[site_verification]
baidu = ""
bing = ""
google = ""
[widgets]
sidebar = ["recent_posts", "taxonomy_category", "taxonomy_tags"]