---
new_page_extension: md
auto_deploy: false
admin_path: ''
webhook_url: 
sections:
- type: heading
  label: Accueil
- type: document
  path: content/french/_index.md
  label: Accueil (fr)
- type: heading
  label: Blog Post
- type: document
  path: content/french/blog/_index.md
  label: Base Post (Fr)
- type: directory
  path: content/french/blog
  label: Post (fr)
  create: documents
  match: "**/*"
  exclude: "**/_index.md"
  templates:
  - post
- type: heading
  label: Auteur
- type: directory
  path: content/french/author
  label: Auteur (fr)
  create: documents
  match: "**/*"
  templates:
  - author
- type: heading
  label: Projet
- type: document
  path: content/french/project/_index.md
  label: Projet (Fr)
- type: heading
  label: Autre Pages
- type: directory
  path: content/french
  label: Autre pages (fr)
  create: documents
  match: "*"
  exclude: _index.md
- type: directory
  path: content/french
  label: Toutes les pages (fr)
  create: all
  match: "**/*"
  templates:
  - new-page
- type: heading
  label: Configurations
- type: document
  path: config/_default/config.toml
  label: Configuration
- type: document
  path: config/_default/params.toml
  label: Paramètres
- type: document
  path: config.toml
  label: Variables & Plugins
- type: document
  path: config/_default/languages.toml
  label: Langage
- type: document
  path: config/_default/menus.fr.toml
  label: Menu (fr)
- type: directory
  path: i18n
  label: i18n Translations
  create: all
  match: "**/*"
upload_dir: static/images
public_path: "/images"
front_matter_path: ''
use_front_matter_path: false
file_template: ":filename:"
build:
  preview_env:
  - HUGO_ENV=staging
  - HUGO_VERSION=0.87.0
  preview_output_directory: public
  preview_docker_image: forestryio/hugo:latest
  mount_path: "/srv"
  working_dir: "/srv"
  instant_preview_command: hugo server -D -E -F --renderToDisk -d public
version: 0.87.0
